inventory/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('new/', views.product_create, name='product_create'),
    path('edit/<int:pk>/', views.product_update, name='product_update'),
    path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_create, name='category_create'),
    path('categories/edit/<int:pk>/', views.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('transactions/new/', views.transaction_create, name='transaction_create'),
    path('transactions/return/create/', views.transaction_return_create, name='transaction_return_create'),
    path('report/', views.report, name='report'),
    path('report/export/', views.export_report_to_excel, name='export_report_to_excel'),
    path('credit_sales/', views.credit_sales_list, name='credit_sales_list'),
    path('credit_sales/new/', views.credit_sale_create, name='credit_sale_create'),
    path('credit_sales/<int:credit_sale_id>/payments/', views.credit_payments_list, name='credit_payments_list'),
    path('credit_sales/<int:credit_sale_id>/payments/new/', views.credit_payment_create, name='credit_payment_create'),
    path('settled_credits/', views.settled_credits, name='settled_credits'),
    path('unsettled_credits/', views.unsettled_credits, name='unsettled_credits'),
    path('credit_return/<int:credit_sale_id>/', views.credit_return, name='credit_return'),
    path('inventory/credit_sales/payments/<int:credit_payment_id>/toggle_paid/', views.credit_payment_toggle_paid, name='credit_payment_toggle_paid'),
    path('credit_payment_create/<int:credit_sale_id>/', views.credit_payment_create, name='credit_payment_create'),
    path('login/', views.custom_login, name='custom_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/inventory/login/'), name='logout'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/edit/', views.supplier_edit, name='supplier_edit'),
    path('suppliers/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),
]

inventory_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
    path('inventory/', include('inventory.urls')),
    path('select2/', include('django_select2.urls')),
    
]

inventory/models.py
from django.db import models
from django.utils import timezone
from decimal import Decimal, ROUND_HALF_UP
from django_countries.fields import CountryField


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    contact_info = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    GENDER_CHOICES = (
        ('М', 'Мужской'),
        ('Ж', 'Женский'),
        ('У', 'Унисекс'),
    )
    gender = models.CharField("Гендер",max_length=1, choices=GENDER_CHOICES, default='У')
    name = models.CharField("Название",max_length=100)
    sku = models.CharField("Артикул",max_length=50, unique=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    manufacturer = models.CharField("Фирма",max_length=100)
    country_of_manufacture = CountryField(blank_label='Выберите страну', verbose_name='Страна производителя', null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Поставщик')
    date_received = models.DateField("Дата поступления",default=timezone.now)
    purchase_price = models.DecimalField("Цена закупки",max_digits=10, decimal_places=2, default=0)
    sale_price = models.DecimalField("Цена",max_digits=10, decimal_places=2)
    discounted_price = models.DecimalField("Цена со скидкой",max_digits=10, decimal_places=2, null=True, blank=True)
    size = models.CharField("Размер", max_length=50, default='0')
    color = models.CharField("Цвет", max_length=50, default='не задан')

    IN_STOCK = 'in_stock'
    SOLD = 'sold'
    WRITTEN_OFF = 'written_off'

    STATUS_CHOICES = [
        (IN_STOCK, 'На складе'),
        (SOLD, 'Продан'),
        (WRITTEN_OFF, 'Списан'),
    ]

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=IN_STOCK,
    )

    def __str__(self):
        return f"{self.sku} - {self.name}"


class InventoryItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)


class CreditSale(models.Model):
    products = models.ManyToManyField(Product, verbose_name='Товары')
    contract_number = models.CharField(max_length=20, unique=True,default=0)
    customer_name = models.CharField(max_length=100,default=0)
    customer_phone = models.CharField(max_length=15,default=0)
    customer_email = models.EmailField(default=0)
    sale_date = models.DateField()
    total_price = models.IntegerField()
    down_payment = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    credit_months = models.PositiveIntegerField(default=12)
    monthly_payment = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    settled = models.BooleanField(default=False)
    _remaining_amount = models.DecimalField(max_digits=10, decimal_places=2,default=0)

    def save(self, *args, **kwargs):
        self.total_price = Decimal(self.total_price).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        super(CreditSale, self).save(*args, **kwargs)

    @property
    def remaining_amount(self):
        return self._remaining_amount

    @remaining_amount.setter
    def remaining_amount(self, value):
        self._remaining_amount = value


class CreditPayment(models.Model):
    credit_sale = models.ForeignKey(CreditSale, on_delete=models.CASCADE)
    payment_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)  # Добавьте это поле

    def __str__(self):
        return f"{self.credit_sale.contract_number} - {self.payment_date}"


class Transaction(models.Model):
    SALE = 'SALE'
    RETURN = 'RETURN'
    WRITE_OFF = 'WRITE_OFF'

    TRANSACTION_TYPES = [
        (SALE, 'Продажа'),
        (RETURN, 'Возврат'),
        (WRITE_OFF, 'Списание'),
    ]

    created_at = models.DateTimeField(default=timezone.now)
    products = models.ManyToManyField(Product, verbose_name='Товары')
    transaction_type = models.CharField(max_length=50, choices=TRANSACTION_TYPES, verbose_name='Тип операции')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')
    total_price = models.FloatField(null=True, blank=True, verbose_name='Общая сумма')
    credit_sale = models.ForeignKey(CreditSale, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Кредитная продажа')

    class Meta:
        verbose_name = 'Транзакция'
        verbose_name_plural = 'Транзакции'

inventory/views.py
import openpyxl, datetime
from django.shortcuts import render, redirect, get_object_or_404, redirect
from .models import (Product, Category, Supplier, Transaction,
                     InventoryItem, CreditSale, CreditPayment,Supplier)
from .forms import (ProductForm, CategoryForm, TransactionForm,
                    CreditSaleForm, CreditPaymentForm, SupplierForm)
from django.contrib import messages
from django.http import HttpResponse
from datetime import timedelta, timezone, datetime, date
from django.urls import reverse
from django.db.models import F, Sum, FloatField, Q, Value, ExpressionWrapper, Case, When, IntegerField, Count, Prefetch, CharField
from django.db.models.functions import Coalesce
from inventory.models import Transaction, CreditSale, Product
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm


 # Лариса Kruglikova3 
 # Галя Vavilonpskov


def is_director(user):
    return user.groups.filter(name="Директор").exists()


def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                if user.groups.filter(name="Директор").exists():
                    request.session['is_director'] = True
                else:
                    request.session['is_director'] = False
                return redirect('product_list')  # замените 'product_list' на название представления главной страницы
            else:
                form.add_error(None, 'Неверный логин или пароль')

    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})  # замените 'login.html' на название шаблона для страницы входа
 # Создание оставшихся платежей автоматически 


@login_required
def product_list(request):
    def get_credit_sales_products():
        credit_sales = CreditSale.objects.all()
        credit_sales_products = set()
        for sale in credit_sales:
            for product in sale.products.all():
                credit_sales_products.add(product)
        return credit_sales_products

    all_products = Product.objects.all()
    credit_sales_products = get_credit_sales_products()

    if request.path == '/inventory/transactions/new/':
        available_products = [product for product in all_products if is_product_available(product) and product not in credit_sales_products]
    else:
        available_products = [product for product in all_products if is_product_available(product)]

    return render(request, 'inventory/product_list.html', {'inventory_items': available_products})


@login_required
@user_passes_test(is_director)
def supplier_list(request):
    suppliers = Supplier.objects.all()
    return render(request, 'inventory/supplier_list.html', {'suppliers': suppliers})


@login_required
@user_passes_test(is_director)
def supplier_create(request):
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('supplier_list')
    else:
        form = SupplierForm()
    return render(request, 'inventory/supplier_form.html', {'form': form, 'form_title': 'Добавить поставщика', 'button_label': 'Сохранить'})


@login_required
@user_passes_test(is_director)
def supplier_edit(request, pk):
    supplier = get_object_or_404(Supplier, pk=pk)
    if request.method == 'POST':
        form = SupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            form.save()
            return redirect('supplier_list')
    else:
        form = SupplierForm(instance=supplier)
    return render(request, 'inventory/supplier_form.html', {'form': form, 'form_title': 'Изменить поставщика', 'button_label': 'Сохранить'})


@login_required
@user_passes_test(is_director)
def supplier_delete(request, pk):
    supplier = get_object_or_404(Supplier, pk=pk)
    if request.method == 'POST':
        supplier.delete()
        return redirect('supplier_list')
    return render(request, 'inventory/supplier_confirm_delete.html', {'supplier': supplier})


@login_required
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, user=request.user)
        if form.is_valid():
            product = form.save()
            InventoryItem.objects.create(product=product)
            return redirect('product_list')
    else:
        form = ProductForm(user=request.user)
    return render(request, 'inventory/product_form.html', {'form': form})


@login_required
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'inventory/product_form.html', {'form': form})


@login_required
@user_passes_test(is_director)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('product_list')
    return render(request, 'inventory/product_confirm_delete.html', {'product': product})


@login_required
@user_passes_test(is_director)
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'inventory/category_list.html', {'categories': categories})


@login_required
@user_passes_test(is_director)
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'inventory/category_form.html', {'form': form})


@login_required
@user_passes_test(is_director)
def category_update(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'inventory/category_form.html', {'form': form})


@login_required
@user_passes_test(is_director)
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('category_list')


@login_required
def transaction_list(request):
    transactions = Transaction.objects.prefetch_related(
        Prefetch('products', queryset=Product.objects.all())
    ).annotate(
        total_discounted_price=Sum('products__discounted_price')
    ).order_by('-created_at')
    context = {
        'transactions': transactions,
    }
    return render(request, 'inventory/transaction_list.html', context)


@login_required
def transaction_create(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            products = form.cleaned_data['products']

            all_products_available = True

            for product in products:
                if transaction.transaction_type == Transaction.RETURN:
                    if product.status == Product.SOLD:
                        product.status = Product.IN_STOCK  # Изменили статус на IN_STOCK
                        product.save()
                    else:
                        all_products_available = False
                        messages.error(request, f'Товар {product.name} уже возвращен или недоступен для возврата.')
                else:
                    if product.status == Product.IN_STOCK:
                        product.status = Product.SOLD if transaction.transaction_type == Transaction.SALE else Product.WRITTEN_OFF
                        product.save()
                    else:
                        all_products_available = False
                        messages.error(request, f'Товар {product.name} недоступен для данной операции.')

            if all_products_available:
                transaction.save()
                for product in products:
                    transaction.products.add(product)  # Теперь добавляем продукты к связи "многие ко многим"
                return redirect('transaction_list')
            else:
                transaction.delete()

    else:
        form = TransactionForm()
    return render(request, 'inventory/transaction_form.html', {'form': form})


@login_required
@user_passes_test(is_director)
def report(request):
    credit_sales = CreditSale.objects.annotate(
        paid_amount=Coalesce(
            Sum('creditpayment__amount', filter=Q(creditpayment__paid=True)), Value(0), output_field=IntegerField()
        ),
    ).annotate(
        remaining_amount_value=ExpressionWrapper(F('total_price') - F('paid_amount'), output_field=IntegerField())
    )

    transaction_type_choices = Transaction._meta.get_field('transaction_type').choices
    transaction_type_dict = dict(transaction_type_choices)

    transactions = Transaction.objects.annotate(
        transaction_type_name=Case(
            *[When(transaction_type=key, then=Value(value)) for key, value in transaction_type_dict.items()],
            output_field=CharField()
        ),
    ).annotate(
        total_discounted_price=Sum('products__discounted_price')
    ).order_by('-created_at')

    in_stock_products = Product.objects.filter(status=Product.IN_STOCK)
    total_in_stock = len(in_stock_products)

inventory/templates/inventory/category_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Список категорий</h2>
  <a href="{% url 'category_create' %}" class="btn btn-primary">Добавить категорию</a>
  <table class="table">
    <thead>
      <tr>
        <th>Наименование</th>
        <th>Описание</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <td>{{ category.name }}</td>
          <td>{{ category.description }}</td>
          <td>
            <a href="{% url 'category_update' category.pk %}" class="btn btn-warning">Редактировать</a>
            <a href="{% url 'category_delete' category.pk %}" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите удалить эту категорию?')">Удалить</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/credit_payments_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Платежи по кредитной продаже {{ credit_sale.contract_number }}</h2>
  <a href="{% url 'credit_payment_create' credit_sale.id %}" class="btn btn-primary">Добавить платеж</a>
  <table class="table">
    <thead>
      <tr>
        <th>Дата платежа</th>
        <th>Сумма платежа</th>
        <th>Статус платежа</th>
      </tr>
    </thead>
    <tbody>
      {% for credit_payment in credit_payments %}
        <tr>
          <td>{{ credit_payment.payment_date }}</td>
          <td>{{ credit_payment.amount }}</td>
          <td>
            {% if credit_payment.paid %}
              <span class="badge badge-success">Оплачено</span>
            {% else %}
            <a href="{% url 'credit_payment_toggle_paid' credit_payment.id %}" class="btn btn-warning">Отметить как оплачено</a>
            {% endif %}
          </td>
          <td>
            {% if credit_payment.paid %}
              <span>Оплачено</span>
            {% else %}
              <span>Не оплачено</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/credit_return.html
{% extends 'base.html' %}

{% block content %}
  <h2>Возврат кредита для продажи {{ credit_sale.contract_number }}</h2>
  <form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите вернуть кредит для продажи {{ credit_sale.contract_number }}?</p>
    <button type="submit" class="btn btn-danger">Да, вернуть</button>
    <a href="{% url 'credit_sales_list' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

inventory/templates/inventory/credit_sale_form.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/custom_styles.css' %}">
    <link rel="stylesheet" href="{% static 'django_select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'django_select2/css/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'django_select2/js/select2.min.js' %}"></script>
    <script src="{% static 'django_select2/js/select2.full.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
    {% with form.products.widget.attrs as attrs %}
    {% with css_classes=attrs.class|default:'' %}
        <select name="{{ form.products.html_name }}" class="{{ css_classes }} form-control" multiple="multiple" id="{{ form.products.auto_id }}">
            {% for product in form.products.field.queryset %}
                <option value="{{ product.pk }}">{{ product }}</option>
            {% endfor %}
        </select>
    {% endwith %}
{% endwith %}
    <script>
      $(document).ready(function() {
          $('select').select2({
              minimumInputLength: 1,
              placeholder: 'Выберите товары'
          });
      });
  </script>
{% endblock %}

{% block content %}
  <h2>Добавить кредитную продажу</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock %}

inventory/templates/inventory/credit_sales_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Кредитные продажи</h2>
  <a href="{% url 'credit_sale_create' %}" class="btn btn-primary">Добавить кредитную продажу</a>
  <table class="table">
    <thead>
      <tr>
        <th>Номер договора</th>
        <th>Товары</th>
        <th>Дата продажи</th>
        <th>Общая сумма</th>
        <th>Оставшаяся сумма</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for credit_sale in credit_sales %}
        <tr>
          <td>{{ credit_sale.contract_number }}</td>
          <td>
            <ul>
              {% for product in credit_sale.products.all %}
                <li>{{ product.sku }} - {{ product.name }}</li>
              {% endfor %}
            </ul>
          </td>
          <td>{{ credit_sale.sale_date }}</td>
          <td>{{ credit_sale.total_price }}</td>
          <td>{{ credit_sale.remaining_amount_value }}</td>
          <td>
            <a href="{% url 'credit_payments_list' credit_sale.id %}" class="btn btn-info">Платежи</a>
            <a href="{% url 'credit_return' credit_sale.id %}" class="btn btn-warning">Возврат кредита</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/product_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Подтверждение удаления товар:</h2>
  <p>Вы уверены, что хотите удалить товар: "{{ product.sku }} - {{ product.name }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'product_list' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

inventory/templates/inventory/product_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Добавить/Редактировать товар</h2>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'product_list' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

inventory/templates/inventory/product_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Список товаров</h2>
  <a href="{% url 'product_create' %}" class="btn btn-primary">Добавить товар</a>
  <table class="table">
    <thead>
      <tr>
        <th>Артикул</th>
        <th>Наименование</th>
        <th>Страна производителя</th>
        <th>Фирма</th>
        {% if request.session.is_director %}
        <th>Поставщик</th>
        {% endif %}
        <th>Женская/Мужская</th>
        <th>Категория</th>
        <th>Дата поступления</th>
        {% if request.session.is_director %}
        <th>Цена закупки</th>
        {% endif %}
        <th>Цена</th>
        <th>Цена со скидкой</th>
        <th>Размер</th>
        <th>Цвет</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for product in inventory_items %}
        <tr>
          <td>{{ product.sku }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.country_of_manufacture.name }}</td>
          <td>{{ product.manufacturer }}</td>
          {% if request.session.is_director %}
          <td>{{ product.supplier }}</td>
          {% endif %}
          <td>{{ product.gender }}</td>
          <td>{{ product.category }}</td>
          <td>{{ product.date_received }}</td>
          {% if request.session.is_director %}
          <td>{{ product.purchase_price }}</td>
          {% endif %}
          <td>{{ product.sale_price }}</td>
          <td>{{ product.discounted_price }}</td>
          <td>{{ product.size }}</td>
          <td>{{ product.color }}</td>
          <td>
            <a href="{% url 'product_update' product.pk %}" class="btn btn-warning">Редактировать</a>
            <a href="{% url 'product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/report.html
{% extends 'base.html' %}

{% block content %}
<h2>Отчет по продажам и списаниям товаров</h2>

<h3>Транзакции:</h3>
<table class="table">
    <thead>
        <tr>
            <th>Товар</th>
            <th>Тип операции</th>
            <th>Общая цена</th>
        </tr>
    </thead>
    <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>
                    {% for product in transaction.products.all %}
                        {{ product.sku }} - {{ product.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>{{ transaction.get_transaction_type_display }}</td>
                <td>{{ transaction.total_discounted_price }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<h3>Кредитные продажи:</h3>
<table class="table">
    <thead>
        <tr>
            <th>Номер договора</th>
            <th>Товары</th>
            <th>Оплачено</th>
            <th>Оставшаяся сумма</th>
        </tr>
    </thead>
    <tbody>
        {% for credit_sale in credit %}
            <tr>
                <td>{{ credit_sale.contract_number }}</td>
                <td>
                    {% for product in credit_sale.products.all %}
                        {{ product.sku }} - {{ product.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>{{ credit_sale.paid_amount }}</td>
                <td>{{ credit_sale.remaining_amount_value }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<h3>Товары на складе:</h3>
<table class="table">
    <thead>
        <tr>
            <th>Товар</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products_in_stock %}
            <tr>
                <td>{{ product.sku }} - {{ product.name }}</td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td style="text-align: right;"><strong>Всего:</strong></td>
            <td>{{ total_in_stock }}</td>
        </tr>
    </tfoot>
</table>

<a href="{% url 'export_report_to_excel' %}" class="btn btn-success">Экспорт в Excel</a>
{% endblock %}

inventory/templates/inventory/supplier_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Подтверждение удаления поставщика</h2>
  <p>Вы уверены, что хотите удалить поставщика "{{ supplier.name }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'supplier_list' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

inventory/templates/inventory/supplier_form.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ form_title }}</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{{ button_label }}</button>
    <a href="{% url 'supplier_list' %}" class="btn btn-secondary">Отмена</a>  <!-- Добавьте эту строку для кнопки "Отмена" -->
  </form>
{% endblock %}

inventory/templates/inventory/transaction_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Список транзакций</h2>
  <a href="{% url 'transaction_create' %}" class="btn btn-primary">Добавить транзакцию</a>
  <table class="table">
    <thead>
      <tr>
        <th>Дата</th>
        <th>Товары</th>
        <th>Артикулы</th>
        <th>Тип операции</th>
        <th>Общая сумма</th> <!-- Добавлен новый заголовок столбца -->
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
        <tr>
          <td>{{ transaction.date }}</td>
          <td>
            {% for product in transaction.products.all %}
              {{ product.name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>
            {% for product in transaction.products.all %}
              {{ product.sku }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>{{ transaction.get_transaction_type_display }}</td>
          <td>{{ transaction.total_discounted_price }}</td> <!-- Добавлен новый столбец для отображения общей суммы -->
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}